{
    "env": "CartPole-v1",
    "total_num_state_transitions": 64,
    "epochs": 2,
    "parallel_agents": 2,
    "param_sharing": True,
    "learning_rate_pol": 0.0001,
    "learning_rate_val": 0.0001,
    "trajectory_length": 5,
    "discount_factor": 0.99,
    "batch_size": 32,
    "clipping_constant": 0.2,
    "entropy_contrib_factor": 0.15,
    "vf_contrib_factor": .9,
    'input_net_type': 'MLP',
    'show_final_demo': True,
}